import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from models.ai_prediction import groq_initialize,predict_disease
from fpdf import FPDF
import os
from database import create_tables, register_user, login_user, save_history, get_history,hash_password,verify_password


if "db_initialized" not in st.session_state:
    create_tables()
    st.session_state.db_initialized = True


if "groq_init" not in st.session_state:
    groq_initialize()
    st.session_state.groq_init = True


def clean_text(text):
    if isinstance(text, list):
        return [clean_text(t) for t in text]

    text = str(text)

    replacements = {
        "\u2011": "-",  # non-breaking hyphen
        "\u2013": "-",  # en dash
        "\u2014": "-",  # em dash
        "\u2018": "'",  
        "\u2019": "'",  
        "\u201c": '"',
        "\u201d": '"',
    }

    for k, v in replacements.items():
        text = text.replace(k, v)

    return text.encode("latin-1", "ignore").decode("latin-1")



def generate_pdf(username, symptoms, recomm, severity, top_dis):
    pdf = FPDF()
    pdf.add_page()

    # HEADER
    pdf.set_fill_color(0, 102, 204)  # Blue header
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "MediPredict Health Report", ln=True, align="C", fill=True)

    pdf.ln(5)

    # Reset text color
    pdf.set_text_color(0, 0, 0)

    # USER DETAILS 
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, clean_text(f"Patient Name: {username}"), ln=True)
    pdf.cell(0, 8, clean_text(f"Symptoms: {symptoms}"), ln=True)

    pdf.ln(5)

    # DISEASE RESULT 
    pdf.set_fill_color(200, 220, 255)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Predicted Disease", ln=True, fill=True)

    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 8, clean_text(f"{top_dis}"), ln=True)

    pdf.ln(5)

    # SEVERITY
    pdf.set_fill_color(255, 230, 200)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Severity Analysis", ln=True, fill=True)

    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 8, clean_text(f"Score: {severity['score']}"), ln=True)
    pdf.cell(0, 8, clean_text(f"Urgency: {severity['urgency']}"), ln=True)
    pdf.cell(0, 8, clean_text(f"Risk Level: {severity['risk_level']}"), ln=True)
    pdf.cell(0, 8, clean_text(f"Action: {severity['action']}"), ln=True)

    pdf.ln(5)

    # RECOMMENDATIONS 
    pdf.set_fill_color(200, 255, 200)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Recommendations", ln=True, fill=True)

    pdf.set_font("Arial", "", 12)

    # Description
    pdf.multi_cell(0, 8, clean_text(f"Description: {recomm['description']}"))

    pdf.ln(2)

    # Precautions
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 8, "Precautions:", ln=True)
    pdf.set_font("Arial", "", 11)
    for p in recomm["precautions"]:
        pdf.cell(0, 8, clean_text(f"- {p}"), ln=True)

    pdf.ln(2)

    # Medications
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 8, "Medications:", ln=True)
    pdf.set_font("Arial", "", 11)
    for m in recomm["medications"]:
        pdf.cell(0, 8, clean_text(f"- {m}"), ln=True)

    pdf.ln(2)

    # Diet
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 8, "Diet:", ln=True)
    pdf.set_font("Arial", "", 11)
    for d in recomm["diet"]:
        pdf.cell(0, 8, clean_text(f"- {d}"), ln=True)

    pdf.ln(2)

    # Workout
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 8, "Workout:", ln=True)
    pdf.set_font("Arial", "", 11)
    pdf.multi_cell(0, 8, clean_text(recomm["workout"]))

    pdf.ln(5)

    # FOOTER 
    pdf.set_text_color(150, 150, 150)
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 10, clean_text("Generated by MediPredict AI | Not a substitute for medical advice"), ln=True, align="C")

    return pdf.output(dest='S').encode('latin-1')


st.set_page_config(page_title="MediPredict",
                   page_icon="🏥",
                   layout="wide")

if "user" not in st.session_state:
    st.session_state.user = None

with st.sidebar:

    # LOGIN
    if st.session_state.user is None:
        st.title("🔐 Login")

        choice = st.radio("Select", ["Login", "Signup"], key="auth_choice")

        username = st.text_input("Username", key="username_input")
        password = st.text_input("Password", type="password", key="password_input")

        
        if choice == "Signup":
            if st.button("Register"):

                if not username or not password:
                    st.error("Username and password required")

                elif len(username) < 3:
                    st.error("Username must be at least 3 characters")

                elif len(password) < 6:
                    st.error("Password must be at least 6 characters")

                elif register_user(username, password):
                    st.success("Account created!")

                else:
                    st.error("Username already exists")


        if choice == "Login":
            if st.button("Login"):

                if not username or not password:
                    st.error("Please enter username and password")

                else:
                    user = login_user(username, password)

                    if user:
                        st.session_state.user = user

                        st.success("Logged in!")
                        st.rerun()
                    else:
                        st.error("Invalid credentials")

    # AFTER LOGIN
    else:
        st.success(f"Logged in as: {st.session_state.user}")

        if st.button("Logout"):
            st.session_state.user = None
            st.rerun()

    st.divider()

if st.session_state.user is None:
    st.info("🔐 Please login from sidebar to continue")
    st.stop()


with st.sidebar:
    st.title("🏥MediPredict")
    st.subheader("AI-powered disease prediction using Machine Learning and NLP")

    st.divider()

    st.subheader("About")
    st.info("Enter your symptoms and get instant disease predictions with confidence scores, recommendations, and severity analysis.")
    
    st.divider()

    st.subheader("Features")
    st.write("✓ Disease Prediction")
    st.write("✓ Confidence Scores")
    st.write("✓ Severity Analysis")
    st.write("✓ Recommendations")
    st.write("✓ PDF Report")

    st.divider()

    st.warning("⚠️ This is NOT a substitute for professional medical advice.")


st.title("🩺 MediPredict AI Health Assistant")
st.write("Describe your symptoms and get instant AI-powered health insights")

col1, col2 = st.columns([3,1])
with col1:
    st.subheader("📝 Enter Your Symptoms")
    text = st.text_area("Describe your symptoms in detail:",
                 placeholder="e.g., fever, cough, headache",
                 help="Be as specific as possible")
    
with col2:
    st.divider()
    

    base_dir = os.path.dirname(__file__)
    image_path = os.path.join(base_dir, "medicalai.jpg")

    if os.path.exists(image_path):
        st.image(image_path)


st.divider()

analysis_button = st.button("🔍 Analyze Symptoms",type="primary")


if analysis_button:
    st.session_state.saved = False   # RESET HERE
    if text:
        with st.spinner("Analysis is in progress.."):
             result = predict_disease(text)
             st.divider()
             st.subheader("🎯 Most Likely Condition")
             
            #  st.success("✅ Analysis Complete!")
        if result is None:
            st.error("Something went wrong, please refresh your page")
        elif "fallback_disease" in result:
            st.subheader("🎯 Most Likely Condition")
            st.success(result["fallback_disease"])
        else:
            predictions = result["predictions"]

            predictions = pd.DataFrame(predictions)
            
            top_disease = predictions.iloc[0]

            st.subheader(top_disease["Disease"])
            st.write(f"Confidence: {top_disease['Confidence']}")
            st.success("✅ Analysis Complete!")

             
            # SAVE ONLY ONCE
            if not st.session_state.get("saved", False):
                save_history(
                    st.session_state.user,
                    text,
                    top_disease["Disease"])
                st.session_state.saved = True


            tab1, tab2, tab3, tab4, tab5 = st.tabs(["📊 Predictions", "💊 Recommendations", "📈 Severity Analysis", "📄 Report", "📜 History"])

            with tab1:
                st.subheader("Top 5 Predicted Conditions")
                bar_chart = px.bar(predictions,
                                x = "Disease",
                                y = "Confidence",
                                title= "Disease Prediction Confidence Levels",
                                color = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd'])
                st.plotly_chart(bar_chart)
            
            with tab2:
                st.subheader(f"Recommendations for {top_disease['Disease']}")
                col1, col2 = st.columns(2)
                recomm = result["recommendations"]
                precautions = recomm["precautions"]
                medications = recomm["medications"]
                diet_list = recomm["diet"]
                workout = recomm["workout"]

                with col1:
                    st.subheader("🛡️ Precautions")
                    for ind,pre in enumerate(precautions):
                        st.markdown(f"{ind+1} {pre}")

                    st.subheader("💊 Medications")
                    for med in medications:
                        st.write(med)

                with col2:
                    st.subheader("🥗 Diet Suggestions")
                    for die in diet_list:
                        st.write(die)

                    st.subheader("🏃 Activity")
                    st.write(workout)
                

            with tab3:
                 st.subheader("📈 Severity Analysis")
                 severity = result["severity"]
                 guage_chart = go.Figure(go.Indicator(
                                    mode = "gauge+number",
                                    value = severity["score"],
                                    title = "Severity Level",
                                    gauge = {
                                        'axis': {'range': [0, 100]},
                                        'bar': {'color': "darkblue"},
                                        'steps': [
                                                 {'range': [0, 25], 'color': "lightgreen"},
                                                 {'range': [25, 50], 'color': "yellow"},
                                                 {'range': [50, 75], 'color': "orange"},
                                                 {'range': [75, 100], 'color': "red"}
                                                 ]
                                            }

                                    ))
                 guage_chart.update_layout(height = 300)
                 st.plotly_chart(guage_chart)

                 col1, col2, col3 = st.columns(3)
                 with col1:
                    st.metric("Urgency",severity["urgency"],"⚠️")
                 with col2:
                    st.metric("Risk Level",severity["risk_level"],"📊")
                 with col3:
                    st.metric("Action",severity["action"],"🏥")
        
            with tab4:
                 st.write("Please download your report")
                 if result:
                     data = generate_pdf(st.session_state.user,
                                          text,
                                          recomm,
                                          result["severity"],
                                          top_disease["Disease"])
                     st.download_button("Download report",
                                   data = data,
                                   mime="application/pdf",
                                   type="primary",
                                   file_name= "report.pdf")

            with tab5:
                st.subheader("📜 Your History")
                history = get_history(st.session_state.user)

                if history:
                    df = pd.DataFrame(history, columns=["Date", "Symptoms", "Disease"])
                    st.dataframe(df)
                else:
                    st.info("No history yet")

    else:
        st.warning("⚠️ Please enter your symptoms before analyzing!")

st.divider()
    
st.caption("MediPredict AI Health Assistant | Powered by Machine Learning & NLP")
st.caption("⚠️ For educational purposes only. Not a substitute for professional medical advice.")




